### ISSUE TITLE
We are working on similar thinks

### ISSUE THREAD

**Issue by GamerClassN7** [markushaug/homify#8]
Hi,
**[me](https://github.com/GamerClassN7)** and **[thebradleysanders](https://github.com/thebradleysanders)** (author of **[IOTSmartHome](https://github.com/thebradleysanders/IOTSmartHome)**) joined the forces and start development of new platform ([Simple-Home](https://github.com/Simple-Home/Simple-Home)) since we both are sharing similar ideas, i From nowhere saw your project **homify**, whitch look awesome :) but same like **[IOTSmartHome](https://github.com/thebradleysanders/IOTSmartHome)** is no longer Actively developed. So i started wondering is you will be interested like **[thebradleysanders](https://github.com/thebradleysanders)** and joined you skill , patience, knowledge, etc.  with ours on similar project :) which is actively worked on :) your contribution would be appreciated :) in any quantity :)

Thank you, for your time!
Best Regards
JonatanRek

**Comment by markushaug** [comment]
Hi Jonatan,

thanks for reaching out to me! And it's pretty cool that you are developing a new SmartHome-Platform in PHP :) 

Homify is already 2 years old, but in my opinion, the concept and its modular approach is a good foundation. I've invested more time in the entire backend logic instead of creating a powerful frontend. Currently, I do not have the time to contribute to other projects, since I have many other development & work topics at SAP.

Since Homify is open-source, you can of course contribute to it / use code out of it. It's licensed under the MIT License, so feel free to use it. (But also credit me, if so).

If you have any questions about my project, feel free to contact me, either via git or also per Mail / LinkedIn

Best regards and good luck with your dev project!

Markus
